# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_MainWindow(object):
    def __init__(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi()

    def show_ui(self): 
        # Loads logging window into optimizartion to display updates
        self.MainWindow.show()
        sys.exit(self.app.exec_())

    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.resize(1500, 1200)
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        style = "QLabel { background-color : black; color : green; }"

        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, 0, 1500, 100))
        self.title.setStyleSheet(style)
        font = QtGui.QFont()
        font.setFamily("consolas")
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setObjectName("title")
        
        self.body = QtWidgets.QLabel(self.centralwidget)
        self.body.setGeometry(QtCore.QRect(0, 100, 1500, 1100))
        self.body.setStyleSheet(style)
        font = QtGui.QFont()
        font.setFamily("consolas")
        font.setPointSize(12)
        self.body.setFont(font)
        self.body.setAutoFillBackground(False)
        self.body.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.body.setObjectName("body")

        self.MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.MainWindow.setMenuBar(self.menubar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "    Optimization running..."))
        self.body.setText(_translate("MainWindow", "     Waiting..."))
    
    def update_title_text(self, message: str):
        # Updates title Qlabel
        self.title.setText("   "+message)

    def update_body_text(self, message: str):
        # Updates body Qlabel
        self.body.setText("     "+message)


if __name__ == "__main__":
    ui = Ui_MainWindow()
    ui.show_ui()
